# Manipulation de données avec la bibliothèque Pandas

- Importer la librairie pandas.
- Lire le fichier "food_info.csv" dans un dataframe qu'on nommera food_info.
- Utiliser l'attribut Dataframe.columns suivi de la méthode Index.tolist() pour retourner une liste contenant tous les noms de colonne de food_info.
- Assigner la liste résultante à la variable col_names et utiliser la fonction print() pour afficher le nom des colonnes.
- Enfin afficher les 3 premiers éléments de food_info.

In [1]:
import pandas as pd
food = pd.read_csv("food.csv")
col_names = food.columns.tolist()
print(col_names)
food.head(3)

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

In [2]:
### cours trasfomrer une colonne
# possible avec + - * /
div_1000 = food["Iron_(mg)"] / 1000
print(div_1000)
iron = food["Iron_(mg)"]

0       0.00002
1       0.00016
2       0.00000
3       0.00031
4       0.00043
         ...
8613    0.00140
8614    0.00058
8615    0.00360
8616    0.00350
8617    0.00140
Name: Iron_(mg), Length: 8618, dtype: float64

In [3]:
### Opération mathématique entre colonnes
water_energy = food["Water_(g)"] * food["Energ_Kcal"]
print(water_energy[0:5])

0    11378.79
1    11378.79
2      210.24
3    14970.73
4    15251.81
dtype: float64

## Transformer une colonne
- Diviser la colonne "Sodium_(mg)" par 1000 pour convertir cette colonne en grammes et assigner le résultat à la variable sodium_grams.
- Multiplier la colonne "Sugar__Tot_(g)" par 1000 pour convertir en milligrammes et assigner le résultat à la variable sugar_milligrams.

In [4]:
sodium_grams = food["Sodium_(mg)"] / 1000
sugar_milligrams = food["Sugar_Tot_(g)"] * 1000

## Opérations mathématiques entre colonnes
- Diviser la colonne "Protein_(g)" par la colonne "Water_(g)" et assigner le résultat à la variable grams_of_protein_per_gram_of_water.
- Additionner les colonnes "Calcium_(mg)" et "Iron_(mg)" et assigner le résultat à la variable milligrams_of_calcium_and_iron.
- Afficher les résultats.

In [5]:
grams_of_protein_per_gram_of_water = food["Protein_(g)"] / food["Water_(g)"]
milligrams_of_calcium_and_iron = food["Calcium_(mg)"] + food["Iron_(mg)"]
print(grams_of_protein_per_gram_of_water)
print(milligrams_of_calcium_and_iron)

0       0.053560
1       0.053560
2       1.166667
3       0.504598
4       0.565313
          ...
8613    0.430233
8614    0.292384
8615    0.000000
8616    0.203283
8617    0.252229
Length: 8618, dtype: float64
0        24.02
1        24.16
2         4.00
3       528.31
4       674.43
         ...
8613     67.40
8614     10.58
8615     16.60
8616     13.50
8617    119.40
Length: 8618, dtype: float64

## Créer un indice nutritionnel

In [6]:
# Score = 2 * (Protein_(g)) - 0.75 * (LipidTot(g))

- Multiplier la colonne "Protein_(g)" par 2 et assigner le résultat à la variable protein.
- Multiplier la colonne "Lipid_Tot_(g)" par -0.75 et assigner le résultat à la variable fat.
- Additionner les variables ensemble et assigner le résultat à la variable rating.
- Afficher le résultat.

In [7]:
protein = food["Protein_(g)"] * 2
fat = food["Lipid_Tot_(g)"] * (-0.75)
rating = protein + fat
print(rating)

0      -59.1325
1      -59.1325
2      -74.0500
3       21.2450
4       24.2200
         ...
8613    18.1750
8614    40.4500
8615     0.0000
8616    31.1500
8617    39.2250
Length: 8618, dtype: float64

### Cours Normaliser les colonnes

In [9]:
# series.max()
# VAaleux max de la colonne
max_calories = food["Energ_Kcal"].max()
print(max_calories)

902

In [10]:
# Diviser les valeures de la colonne #Energ_Kcal# par la valeur max de cette même colonne
normalized_calories = food["Energ_Kcal"] / max_calories
print(normalized_calories)

0       0.794900
1       0.794900
2       0.971175
3       0.391353
4       0.411308
          ...
8613    0.338137
8614    0.123060
8615    0.298226
8616    0.099778
8617    0.098670
Name: Energ_Kcal, Length: 8618, dtype: float64

## Normaliser des colonnes
- Normaliser les valeurs de la colonne "protein_(g)" et assigner le résultat à la variable normalized_protein.
- Normaliser les valeurs de la colonne "Lipid_Tot_(g)" et assigner le résultat à la variable normalized_fat.

In [18]:
max_protein = food["Protein_(g)"].max()
normalized_protein = food["Protein_(g)"] / max_protein
print(normalized_protein)
normalized_lipid = food["Lipid_Tot_(g)"] / food["Lipid_Tot_(g)"].max()
print(normalized_lipid)

0       0.009624
1       0.009624
2       0.003170
3       0.242301
4       0.263134
          ...
8613    0.209466
8614    0.232563
8615    0.000000
8616    0.182292
8617    0.224185
Name: Protein_(g), Length: 8618, dtype: float64
0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
         ...
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

### Cours creer une nouvelle colonne

In [20]:
iron_grams = food["Iron_(mg)"] / 1000
food["Iron_(g)"] = iron_grams
food

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.00002
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.00016
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.00000
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.00031
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.00043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.00140
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.00058
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.00360
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.00350
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.00140

## Créer une nouvelle colonne
- Assigner la colonne normalisée représentée par la variable normalized_protein à la nouvelle colonne qu'on nommera "Normalized_Protein" dans le dataframe food_info.
- Assigner la colonne normalisée représentée par la variable normalized_fat à la nouvelle colonne qu'on nommera "Normalized_Fat" dans la dataframe food_info.
- Afficher les 5 premières valeurs du dataframe food_info.

In [25]:
food["Normalized_Protein"] = normalized_protein
food["Normalized_Fat"] = normalized_lipid
food.head(5)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.00002,0.009624,0.8111
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.00016,0.009624,0.8111
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.00000,0.003170,0.9948
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.00031,0.242301,0.2874
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.00043,0.263134,0.2968

## Créer une colonne pour l'indice nutritionnel normalisé

- Utiliser les colonnes Normalized_Protein et Normalized_Fat avec cette formule pour créer une nouvelle colonne qu'on nommera Norm_Nutr_Index.

In [30]:
food["Normalized_Protein"] = normalized_protein
score = 2 * normalized_protein - (0.75 * normalized_lipid)
food["Norm_Nutr_Index"] = score
food.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,51.368,21.021,3.043,215.0,0.00002,0.009624,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,50.489,23.426,3.012,219.0,0.00016,0.009624,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,73.0,8.6,61.924,28.732,3.694,256.0,0.00000,0.003170,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,21.0,2.4,18.669,7.778,0.800,75.0,0.00031,0.242301,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,22.0,2.5,18.764,8.598,0.784,94.0,0.00043,0.263134,0.2968,0.303668

### Cours trier un dataFrame

In [38]:
# sort_values()
food.sort_values("Sodium_(mg)")
# trie et remplace le dataframe
food.sort_values("Sodium_(mg)", inplace= True)
food.head()
# trie décroisssant
food.sort_values("Sodium_(mg)", inplace= True, ascending = False)
food.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
276,2047,SALT TABLE,0.20,0,0.00,0.00,99.8,0.0,0.0,0.00,...,0.0,0.0,0.000,0.000,0.000,0.0,0.00033,0.000000,0.0000,0.000000
5814,18372,LEAVENING AGENTS BAKING SODA,0.20,0,0.00,0.00,36.9,0.0,0.0,0.00,...,0.0,0.0,0.000,0.000,0.000,0.0,0.00000,0.000000,0.0000,0.000000
6192,19225,DESSERTS RENNIN TABLETS UNSWTND,6.50,84,1.00,0.10,72.5,19.8,0.0,NaN,...,NaN,NaN,0.041,0.038,0.007,0.0,0.00707,0.011322,0.0010,0.021895
1242,6075,SOUP BF BROTH OR BOUILLON PDR DRY,3.27,213,15.97,8.89,54.5,17.4,0.0,16.71,...,0.0,3.2,4.320,3.616,0.332,10.0,0.00100,0.180820,0.0889,0.294964
1245,6081,SOUP CHICK BROTH CUBES DRY,2.50,198,14.60,4.70,54.7,23.5,0.0,0.00,...,NaN,0.0,1.200,1.920,1.620,13.0,0.00187,0.165308,0.0470,0.295366

## Trier un DataFrame
- Remplacer le dataframe food_info en triant par rapport à la colonne Norm_Nutr_Index de façon décroissante (du plus grand au plus petit)

In [39]:
food.sort_values("Norm_Nutr_Index", inplace= True, ascending = False)
food.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.0,0.066,0.101,0.258,0.0,0.01450,1.000000,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.0,0.070,0.060,0.010,0.0,0.00111,0.969203,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.0,0.147,0.173,0.070,20.0,0.00023,0.958220,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.0,0.000,0.000,0.000,0.0,0.00024,0.932971,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,NaN,0.600,1.330,0.370,NaN,0.04960,0.935236,0.0230,1.853221